### ISSUE TITLE
A few issues I encountered

### ISSUE THREAD

**Issue by angusmcleod** [gauravchl/ansi-art#2]
Cool this is fun :) Got it working, but I had to make the following changes from your examples.

1. ``require`` instead of ``import``. 
2. ``ANSI.default.get`` instead of ``ANSI.get``

So I ended up with:

ansi-script.js
```
let ANSI = require('ansi-art');
let mario = ANSI.default.get({artName: 'mario'});
```

Which worked :)

<img width="444" alt="screen shot 2017-05-31 at 10 16 56 pm" src="https://cloud.githubusercontent.com/assets/5931623/26636305/e98cf4f8-464e-11e7-8fb1-3b40043fb067.png">

**Comment by gauravchl** [comment]
@angusmcleod Cool! Thanks.

Examples are in ES6 module that no js engine natively supports it yet. If you are using Babel, Babel actually converts import and export declaration to CommonJS (require/module.exports).
updated readme with node's require module(CommonJS) example: https://github.com/gauravchl/ansi-art/commit/6c901a2d018c7742dd01e98b57e24245021a67d7

Cheers 🍻
