### ISSUE TITLE
Problems showing long text in limited space

### ISSUE THREAD

**Issue by mojoaxel** [gauravchl/ansi-art#6]
_Thanks for creating ansi-art!_

Working on [tiny-care-terminal](https://github.com/notwaldorf/tiny-care-terminal/issues/139) I noticed that long text are not displayed very nicely there is not enought space:

![image](https://user-images.githubusercontent.com/600565/37524932-a9890c00-292b-11e8-8adb-7888c83196cc.png)
Maybe some better word-wrap could be introduced!?

_It's not a big think but I thought It should be tracked here._

**Comment by gauravchl** [comment]
@mojoaxel My pleasure :) 
I'll try to find if there is any responsive way to wrap the text with dashed lines.

**Comment by mojoaxel** [comment]
As an inspiration - this is how [yoman](https://github.com/yeoman/yosay) handles this issue (The boy can grow downwards):

![screen shot 2018-03-22 at 9 37 39 am](https://user-images.githubusercontent.com/976391/37784308-b34be8a6-2db4-11e8-9eb5-282243072eae.png)

**Comment by gauravchl** [comment]
This is fixed in [v1.2.3](https://github.com/gauravchl/ansi-art/releases/tag/v1.2.3)

**Comment by mojoaxel** [comment]
:tada: Thx!

**Comment by fluxsauce** [comment]
Yay, thank you!
